services:
  app:
    image: payload-demo
    ports:
      - "3000:3000"
    env_file: .env.production
    volumes:
      - ./data:/app/data
      - ./public/media:/app/public/media
    restart: unless-stopped
